[profile.release]
codegen-units = 1
lto = true
strip = "symbols"

[workspace]
resolver = "2"
members = [
    "crates/blocks_report",
    "crates/blocks_report_data",
    "crates/macros",
    "crates/minecraft_packets",
    "crates/minecraft_protocol",
    "crates/net",
    "crates/pico_binutils",
    "crates/pico_structures",
    "crates/pico_text_component",
    "crates/protocol_version",
    "crates/protocol_version_macro",
    "pico_libraries/pico_identifier",
    "pico_libraries/pico_nbt",
    "pico_libraries/pico_precomputed_registries",
    "pico_libraries/pico_registries",
    "pico_lobby",
]

[workspace.dependencies]
anyhow = "1.0.104"
base64 = "0.23.1"
byteorder = "1.5.0"
clap = { version = "4.6.7", features = ["derive"] }
flate2 = "1.1.10"
futures = "0.3.34"
hmac = "0.13.0"
indexmap = { version = "2.14.2", features = ["serde"] }
md5 = { package = "md-5", version = "0.11.0" }
phf = { version = "0.14.0", features = ["macros"] }
phf_codegen = "0.14.0"
proc-macro2 = "1.0.107"
quick-xml = "0.42.0"
quote = "1.0.47"
rand = "0.10.3"
rayon = "1.12.0"
regex = "1.13.1"
reqwest = { version = "0.13.5", default-features = false, features = ["json", "rustls", "http2"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_bytes = "0.11.19"
serde_json = "1.0.151"
serde_test = "1.0.177"
sha2 = "0.11.0"
subtle = "2.6.1"
syn = { version = "3.0.6", features = ["full"] }
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["rt", "rt-multi-thread", "macros", "io-util", "net", "time", "sync", "signal"] }
tokio-util = { version = "0.7.19", features = ["rt"] }
toml = "1.1.6"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
uuid = { version = "1.26.1", features = ["v4"] }
walkdir = "2.5.0"
