[versions]
jna = "5.19.1"
velocity = "3.5.1"
bungeecord = "26.1-R0.1-SNAPSHOT"

[libraries]
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
velocity = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }
bungeecord = { module = "net.md-5:bungeecord-api", version.ref = "bungeecord" }
